layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

topics:
  - name: Angular
    web_url: https://github.com/angular/angular
    image_url: https://avatars0.githubusercontent.com/u/139426?s=200&v=4
    
  - name: Java
    image_url: https://upload.wikimedia.org/wikipedia/en/thumb/3/30/Java_programming_language_logo.svg/1200px-Java_programming_language_logo.svg.png
    
  - name: Spring Boot
    web_url: https://spring.io/projects/spring-boot
    image_url: https://spring.io/img/spring-by-pivotal-9066b55828deb3c10e27e609af322c40.png
    
  - name: Python
    web_url: https://www.python.org/
    image_url: https://banner2.kisspng.com/20180412/kye/kisspng-python-programming-language-computer-programming-language-5acfdc3636bac7.8891188615235717662242.jpg

theme: jekyll-theme-minimal
